package com.inotter.travelcompanion.data.datasources.videolibrary.models

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an upload session for TUS resumable uploads.
 * Tracks the state of uploads that may be interrupted (e.g., by power loss, network issues).
 *
 * This entity maps to the tus-java-server UploadInfo structure and stores:
 * - TUS protocol metadata (tusUploadId, uploadUrl)
 * - File metadata (filename, size, mimeType)
 * - Progress tracking (bytesReceived)
 * - MediaStore reference for the pending file
 *
 * @property id Auto-generated primary key
 * @property tusUploadId Unique TUS upload ID (UUID generated by tus-java-server)
 * @property uploadUrl Full TUS upload URL for resume operations (maps to UploadInfo.uploadUrl)
 * @property filename Original filename being uploaded
 * @property expectedSize Total expected file size in bytes
 * @property bytesReceived Number of bytes successfully written to MediaStore (TUS offset)
 * @property mediaStoreUri Content URI of the pending MediaStore entry (IS_PENDING=1)
 * @property mimeType MIME type of the file (e.g., "video/mp4")
 * @property createdAt Timestamp when the upload session was created (epoch millis)
 * @property lastUpdatedAt Timestamp of last progress update (epoch millis)
 * @property status Current status of the upload session
 */
@Entity(
    tableName = "upload_sessions",
    indices = [
        Index(value = ["tusUploadId"], unique = true),
        Index(value = ["uploadUrl"], unique = true),
        Index(value = ["mediaStoreUri"], unique = true)
    ]
)
data class UploadSession(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val tusUploadId: String,
    val uploadUrl: String,
    val filename: String,
    val expectedSize: Long,
    val bytesReceived: Long = 0,
    val mediaStoreUri: String,
    val mimeType: String,
    val createdAt: Long = System.currentTimeMillis(),
    val lastUpdatedAt: Long = System.currentTimeMillis(),
    val status: UploadSessionStatus = UploadSessionStatus.IN_PROGRESS
) {
    /**
     * Returns the upload progress as a percentage (0-100).
     */
    val progressPercent: Int
        get() = if (expectedSize > 0) {
            ((bytesReceived * 100) / expectedSize).toInt().coerceIn(0, 100)
        } else 0

    /**
     * Returns true if this upload session has expired (older than 24 hours).
     * TUS protocol sessions expire after 24 hours per specification.
     */
    fun isExpired(): Boolean =
        System.currentTimeMillis() - createdAt > EXPIRATION_MILLIS

    /**
     * Returns true if this upload session appears to be orphaned
     * (in progress but no activity for specified duration).
     */
    fun isOrphaned(maxAgeMillis: Long = EXPIRATION_MILLIS): Boolean {
        return status == UploadSessionStatus.IN_PROGRESS &&
               System.currentTimeMillis() - lastUpdatedAt > maxAgeMillis
    }

    companion object {
        /** 24 hours in milliseconds - TUS session expiration time */
        const val EXPIRATION_MILLIS = 24 * 60 * 60 * 1000L
    }
}

/**
 * Status of an upload session.
 */
enum class UploadSessionStatus {
    /** Upload is currently in progress */
    IN_PROGRESS,
    /** Upload completed successfully */
    COMPLETED,
    /** Upload failed and was cleaned up */
    FAILED,
    /** Upload was cancelled by user */
    CANCELLED
}

